#!/bin/bash

function block_for_change {
  inotifywait --recursive --event modify,move,create,delete \
      --excludei .git* --quiet \
      *.c *.h Makefile
}
function build {
    make check
}
build
while block_for_change; do
  build
done
